# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_profile_profile_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='flow_index',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
