# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20160415_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='flow',
            name='flow_index',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.Flow'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.Profile'),
        ),
    ]
