# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20160418_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=20)),
                ('test_for_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.Flow')),
                ('test_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Subject')),
            ],
        ),
    ]
