# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_for_flow',
        ),
    ]
