# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_remove_test_test_for_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='test_app.Subject'),
        ),
    ]
