# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_auto_20160419_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_num_select',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_flow', to='test_app.Flow'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_tutors', to='test_app.Profile'),
        ),
    ]
