# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import test_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_auto_20160423_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_file',
            field=models.FileField(blank=True, null=True, upload_to=test_app.models.test_directory_path),
        ),
    ]
