# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_test_test_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
