# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=127)),
                ('answer_is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('V', 'Variable'), ('S', 'Single'), ('I', 'Input')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_for_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='test_app.Test'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_answers',
            field=models.ManyToManyField(related_name='answer_questions', to='test_app.Answer'),
        ),
    ]
