# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
