# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0017_auto_20160429_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_min',
            new_name='test_2',
        ),
    ]
