# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0018_auto_20160429_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Profile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Test')),
            ],
        ),
    ]
