# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0019_test_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(max_length=127)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Question')),
            ],
        ),
        migrations.RenameModel(
            old_name='Test_complete',
            new_name='TestComplete',
        ),
        migrations.AddField(
            model_name='testselection',
            name='test_complete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.TestComplete'),
        ),
    ]
