# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0021_auto_20160430_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcomplete',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.Profile'),
        ),
        migrations.AlterField(
            model_name='testcomplete',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.Test'),
        ),
    ]
