# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0023_testcomplete_num_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testselection',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testselection',
            name='student_answer',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
