# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0025_testcomplete_correct_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcomplete',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
