# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0027_test_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='translite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
