# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0028_test_translite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='translite',
        ),
    ]
