# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0029_remove_test_translite'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='translit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
